# https://docs.travis-ci.com/user/customizing-the-build/
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.1
notifications:
  recipients:
    - nesquena@gmail.com
    - databyte@gmail.com
before_install:
  - gem install bundler
gemfile:
  - gemfiles/activesupport_4_0.gemfile
  - gemfiles/activesupport_4_1.gemfile
  - gemfiles/activesupport_4_2.gemfile
  - gemfiles/activesupport_5_0.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/activesupport_5_0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activesupport_5_0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/activesupport_5_0.gemfile
